package com.stumac.financemanager.service.accounts;

import lombok.Builder;
import lombok.Getter;
import org.springframework.format.annotation.NumberFormat;

import java.math.BigDecimal;

import static org.springframework.format.annotation.NumberFormat.Style.CURRENCY;

@Getter
@Builder
public class ProfitAndLoss {

    /**
     * Revenue generated by working for clients.
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal sales;

    /**
     * Costs incurred during delivery of services.
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal costOfSales;

    /**
     * Sales less cost of sales.
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal grossProfit;

    /**
     * Other forms of income (e.g. bank interest)
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal otherIncome;

    /**
     * Day to day expenses incurred (e.g. salary, travel).
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal expenses;

    /**
     * Gross profit plus other income less expenses.
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal profitBeforeTax;

    /**
     * Tax paid on net profit at a rate of 20%.
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal corporationTax;

    /**
     * Profit before tax less corporation tax.
     */
    @NumberFormat(style = CURRENCY)
    private BigDecimal netProfit;
}
