---
spring:
  datasource:
    schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
    url: jdbc:mysql://mysql:3306/finance-manager
    username: ${MYSQL_ENV_MYSQL_USER}
    password: ${MYSQL_ENV_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
