---
management:
  context-path: /admin
  info:
    git:
      mode: full
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  jpa:
    ddl-auto: update
    show-sql: true
